name: Practice

on:
  push

jobs:
  Buildjob:
    runs-on: ubuntu-latest
    steps:
      - name: 1st phase
        uses: actions/checkout@v3
      
      - name: 2nd phase
        run: |
          mkdir rakesh 
  
  Deployjob:
    runs-on: ubuntu-latest
    needs: Buildjob
    steps:
      - name: 3rd phase
        run: |
          echo "file created"
        




