name: Practice

on:
  push

jobs:
  Buildjob:
    runs-on: ubuntu-latest
    steps:
      - name: 1st phase
        uses: actions/checkout@v3
      
      - name: 2nd phase
        run: |
          mkdir BB
          echo "my line" > BB/bby.txt
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          git add BB/bby.txt
          git commit -m "Create folder using GitHub Actions"
          git push https://github.com/${{ github.repository }}.git HEAD:main
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
  
  Deployjob:
    runs-on: ubuntu-latest
    needs: Buildjob
    steps:
      - name: 3rd phase
        run: |
         cat BB/bby.txt

  artifact:
    runs-on: ubuntu-latest
    needs: Deployjob

    steps:
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bby-file-text
          path: bby.txt
      
      - name: upload artifact
        uses: actions/download-artifact@v4
        with:
          name: bby-file-text
        


 






