name: Practice

on:
  push

jobs:
  Buildjob:
    runs-on: ubuntu-latest
    steps:
      - name: 1st phase
        uses: actions/checkout@v3
      
      # - name: 2nd phase
      #   run: |
      #     mkdir BB
      #     echo "Love you BB....!" > BB/bby.txt
      #     git config --global user.email "no-reply@github.com"
      #     git config --global user.name "GitHub Actions"
      #     git add BB/bby.txt
      #     git commit -m "Create folder using GitHub Actions"
      #     git push
  
  # Deployjob:
  #   runs-on: ubuntu-latest
  #   needs: Buildjob
  #   steps:
  #     - name: 3rd phase
  #       run: |
  #        echo BB/bby.txt

  Artifact:
    runs-on: ubuntu-latest

    steps:
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bby-file-text
          path: BB/bby.txt
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: bby-file-text
        


 






