name: Practice

on:
  push

jobs:
  Buildjob:
    runs-on: ubuntu-latest
    steps:
      - name: 1st phase
        uses: actions/checkout@v3
      
      - name: 2nd phase
        run: |
          mkdir BB 
  
  Deployjob:
    runs-on: ubuntu-latest
    needs: Buildjob
    steps:
      - name: 3rd phase
        run: |
         echo "my line" > bby.txt
         cat bby.txt

  artifact:
    runs-on: ubuntu-latest
    needs: Deployjob

    steps:
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bby-file-text
          path: bby.txt
      
      - name: upload artifact
        uses: actions/download-artifact@v4
        with:
          name: bby-file-text
        


 






