name: Greetings

on:
  workflow_dispatch:

jobs:
  workflow_call:
    strategy:
      matrix:
        input1:[1,3,4]
        input2:[7,8,9]
    uses: ./.github/workflows/reusable_workflow.yml 
    with:
      set_values1: ${{matrix.input1}}
      set_values2: ${{matrix.input2}}
