name: Reusable workflow example

on:
  workflow_call:
    inputs:
      set_values1:
        required: true
        type: string
      set_values2:
        required: true
        type: string
        
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - name: calling the input from caller workflow
        run: | 
          echo "Log level: ${{ inputs.set_values1 }}"
          echo "Tags: ${{ inputs.set_values2}}" 
